actions = {
    "AGENT_WAKES":"AGENT_WAKES",
    "AGENT_OBSERVES_SELF":"AGENT_OBSERVES_SELF",
    "AGENT_SLEEPS":"AGENT_SLEEPS",
    "AGENT_USES_BATHROOM": "AGENT_USES_BATHROOM",
    "AGENT_KILLS_REV":"AGENT_KILLS_REV"
}